17 übergang von sqlite zu shared preferences
sorrowcode/taesch- pull request #33
Opened 2022-11-06 10:55 UTC by jonycoo

on update replace in storage,
filter query
add shared_preferences dependency

2022-11-06 17:00 UTC, sorrowcode requested changes
Bitte noch die Unit-Tests schreiben mit einer möglichen Verwendung der Schnittstelle

2022-11-08 04:41 UTC, sorrowcode submitted a review, later dismissed
developer in den eigenen Branch hinzufügen für neue Funktionalität

2022-11-10 16:07 UTC, jonycoo commented
yes I was too impatient with the push

2022-11-13 06:07 UTC, sorrowcode approved these changes

2022-11-13 06:07 UTC, merged