47 feature verbindung nearshopsscreen und mapscreen
sorrowcode/taesch- pull request #68
Opened 2022-11-29 16:28 UTC by RedConcrete

all done

2022-11-29 16:33 UTC, RedConcrete commented
LETS GO hat auf anhieb geklappt
👯 👍 👯

2022-11-29 16:34 UTC, sorrowcode requested changes
Hier fehlen mir Tests, die die Funktionalität validieren, bitte nacharbeiten.

2022-11-29 16:45 UTC, sorrowcode requested changes
Leider habe ich die Funktionalität bei mir aus folgendem Grund nicht prüfen können:

![image](https://user-images.githubusercontent.com/58072297/204590160-196da14c-ab0d-4b99-aabb-5e5bca0f4aa7.png)

Bei dem Aufruf der Shops jedoch im developer wird dieser Fehler bei mir nicht aufgerufen. Hier wäre ein sinnvolles Exception-Handling angebracht.

Vielleicht kann dir @maximilianley aushelfen.

2022-12-05 16:28 UTC, RedConcrete commented
Kann erst weiter machen wenn der BUG #59 gefixed wurde !!!!!

2022-12-05 16:46 UTC, RedConcrete commented
![image](https://user-images.githubusercontent.com/58186633/205693924-9fc2186d-0c62-4955-9e44-0a827e6d21dc.png)

2022-12-08 17:44 UTC, RedConcrete commented
![image](https://user-images.githubusercontent.com/58186633/206525313-e1365ba2-a898-4132-899f-3f50f189d824.png)

2022-12-09 08:48 UTC, sorrowcode approved these changes

2022-12-09 08:48 UTC, merged

2022-12-09 08:49 UTC, RedConcrete commented
![giphy](https://user-images.githubusercontent.com/58186633/206662275-f6958069-c09b-4ba2-8bc9-843f8ff9e3b1.gif)

finally!!!!!!!!!!!!!!!!!!